language: node_js

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libavahi-compat-libdnssd-dev

node_js:
- '4'
- '0.12'
- '0.10'

matrix:
  allow_failures:
    - node_js: '4'
    - node_js: '0.12'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libasound2-dev
